import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
    
      <style jsx>{`
      h2{
        font-size: 38px
      }
      h3{
        font-size: 28px
      }
      `}</style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <mate name='keywords' content="next.js , huntingcoder blog, hunting coder"/>
        <link rel="icon" href="/favicon.ico" />
        {/* <script src='sc.js'></script> */}
      </Head>
{/* <Script src='/sc.js' strategy='lazyOnload'></Script> */}
    
      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className=''>   Hunting Coder</span>
        </h1>
        <div className={styles.imagewrap}>

{/* <Image className={styles.myimg} src="/homeimg.jpg"  width={237} height={158}/> */}
<img className={styles.myimg}   src="/homeimg.jpg" width={237} height={158} ></img>
        </div>
        <p className={styles.description}>
          A blog for hunting cogers by a hunting coder 
        </p>

      <div className={styles.con}>
        <h2>Popular Blogs</h2>
        <div className="blogeItem">
          <h3>How to learn JavaScript in 2022?</h3>
          <p>JavaScript is the language used to design logic for the web</p>
        </div>
        <div className="blogeItem">
          <h3>How to learn JavaScript in 2022?</h3>
          <p>JavaScript is the language used to design logic for the web</p>
        </div><div className="blogeItem">
          <h3>How to learn JavaScript in 2022?</h3>
          <p>JavaScript is the language used to design logic for the web</p>
        </div>
      </div>
    
      
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
